feat: updated info to reflect Stacks 2.0 ecosystem
friedger/awesome-stacks pull request #5
Opened 2021-05-24 17:53 UTC by pgray-hiro

Initial content for an Awesome Stacks page for Stacks 2.0.  This is meant to be a base seed that the community can start contributing to.

2021-05-24 23:28 UTC, friedger requested changes
The updates looks quite Hiro biased :-) Maybe we just update the structure and then add awesome content

2021-05-24 23:28 UTC, friedger commented on README.md
> +## Clarity Resources
Maybe better ## Awesome Clarity Resources

2021-05-25 18:21 UTC, pgray-hiro commented on README.md
> +- **[Daemon Technologies](https://daemontechnologies.co):** Mining bot for STX mining
Do you think we should remove this entirely for now? Or maybe move the entry lower in the document to a `## Companies` section?

2021-05-25 18:57 UTC, pgray-hiro commented
@friedger Let me know what you think of the changes I made. I'm still learning the ecosystem so if I'm missing something it's probably because I don't know about it rather than an intentional omission.

2021-05-30 20:44 UTC, friedger approved these changes
Let's merge it and continue from here.

2021-05-30 20:44 UTC, friedger commented on README.md
> +- **[This is #1](https://www.thisisnumberone.com):** The first NFT built on Bitcoin and the Stacks blockchain ([contract](https://explorer.stacks.co/txid/SP3QSAJQ4EA8WXEDSRRKMZZ29NH91VZ6C5X88FGZQ.thi
Not true, there are NFTs that exists before that.

2021-05-30 20:44 UTC, friedger commented on README.md
> +## Companies
Does it make sense to list companies?

2021-05-30 20:44 UTC, merged